# Generated by Django 4.1.7 on 2026-02-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories_target',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty_level',
            field=models.CharField(default='Intermediate', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
